CREATE TABLE AGGR_ORDER_20151203
SELECT 	erp_invoice_id,
		COUNT(item_id) AS num_of_items,
		user_id,
		created,
		payment_method,
		shipping_method,
		related_division,
		currency,
		exchange_rate_of_currency,
		item_vat_rate,
		SUM(item_net_purchase_price_in_base_currency) AS item_net_purchase_price_in_base_currency,
		SUM(item_net_sale_price_in_currency) AS item_net_sale_price_in_currency,
		SUM(item_gross_sale_price_in_currency) AS item_gross_sale_price_in_currency,
		SUM(item_net_sale_price_in_base_currency) AS item_net_sale_price_in_base_currency,
		SUM(item_gross_sale_price_in_base_currency) AS item_gross_sale_price_in_base_currency,
		SUM(item_quantity) AS item_quantity,
		SUM(item_revenue_in_local_currency) AS item_revenue_in_local_currency,
		SUM(item_vat_value_in_local_currency) AS item_vat_value_in_local_currency,
		SUM(item_revenue_in_base_currency) AS item_revenue_in_base_currency,
		SUM(item_vat_in_base_currency) AS item_vat_in_base_currency,
		SUM(item_gross_revenue_in_base_currency) AS item_gross_revenue_in_base_currency,
		SUM(item_weight_in_kg) AS item_weight_in_kg,
		user_type,
		province,
		city_size,
		gender,
		reminder_day,
		SUM(revenues_wdisc_in_local_currency) AS revenues_wdisc_in_local_currency,
		SUM(revenues_wdisc_in_base_currency) AS revenues_wdisc_in_base_currency,
		SUM(gross_margin_wodisc_in_base_currency) AS gross_margin_wodisc_in_base_currency,
		SUM(gross_margin_wdisc_in_base_currency) AS gross_margin_wdisc_in_base_currency,
		newsletter,
		cohort_id,
		invoice_yearmonth,
		invoice_year,
		invoice_month,
		invoice_day_in_month,
		cohort_month_since,
		user_cum_transactions,
		user_cum_gross_revenue_in_base_currency,
		order_date_and_time,
		order_year,
		order_month,
		order_day_in_month,
		order_weekday,
		order_week_in_month,
		packaging_deadline,
		related_webshop,
		marketing_channel,
		SUM(order_value) AS order_value,
		SUM(net_margin_wodisc_in_base_currency) AS net_margin_wodisc_in_base_currency,
		SUM(net_margin_wdisc_in_base_currency) AS net_margin_wdisc_in_base_currency,
		SUM(shipping_cost_in_base_currency) AS shipping_cost_in_base_currency,
		SUM(packaging_cost_in_base_currency) AS packaging_cost_in_base_currency,
		SUM(payment_cost_in_base_currency) AS payment_cost_in_base_currency
		

		
		
FROM `BASE_08_TABLE`
GROUP BY erp_invoice_id